image: node:16.14.2

pipelines:
  branches:
    master:

      - step:
          name: Install NPM packages and build NestJS
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/**

      - step:
          name: Deploy to Firebase Functions
          deployment: production
          script:
            - pipe: atlassian/firebase-deploy:1.3.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                EXTRA_ARGS: '--only functions'
                PROJECT_ID: $FIREBASE_PROJECT_ID