"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const app_middleware_1 = require("./../app.middleware");
const express_1 = require("express");
const auth_controller_1 = require("./auth.controller");
const auth_middleware_1 = require("./auth.middleware");
const router = (0, express_1.Router)();
router.use('/user', (0, app_middleware_1.CacheMiddleWare)('5 minutes'), auth_middleware_1.AuthMiddleware);
router.get('/user', auth_controller_1.CurrentUserController);
router.post('/login', auth_controller_1.LoginController);
router.get('/logout', auth_controller_1.LogoutController);
exports.default = router;
