name: '🧳 End to End Test'

on: 
  workflow_call:

jobs:
  build:
    name: End to End Test project
    runs-on: ubuntu-latest
    steps:
      
      - name: ✅ Checkout branch
        uses: actions/checkout@v3
      
      - name: 🤖 Use Node.js
        id: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
          cache: npm

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: 🧨 Install NPM dependencies
        if: steps.cache-npm.outputs.cache-hit != true
        run: npm ci

      - name: Create firebase.sdk.client.key.json file
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "firebase.sdk.client.key.json"
          json: ${{ secrets.FIREBASE_SDK_CLIENT_KEY }}
          dir: 'src/environmnet'

      - name: 💫 End to End testing
        run: echo "hola mundo"