name: '🧳 Test'

on: 
  workflow_call:
    inputs:
      browser:
        required: true
        type: boolean
      server:
        required: true
        type: boolean

jobs:
  build:
    name: Test project
    runs-on: ubuntu-latest
    steps:
      
      - name: ✅ Checkout branch
        uses: actions/checkout@v3
      
      - name: 🤖 Use Node.js
        id: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
          cache: npm

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: 🧨 Install NPM dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      - name: 💫 Run unit testing
        if: inputs.server == 'true'
        run: npm run test
        #run: |
          #npx nyc jasmine
          #npx nyc report --reporter=html -t coverage --report-dir=coverage/server

      #- name: Archive Production Artifact
        #if: inputs.server == 'true'
        #uses: actions/upload-artifact@master
        #with:
          #name: coverage_server
          #path: coverage/server

      - name: 💫 Run unit testing
        if: inputs.browser == 'true'
        run: npx @angular/cli test -- --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage

      - name: Archive Production Artifact
        if: inputs.browser == 'true'
        uses: actions/upload-artifact@master
        with:
          name: coverage_browser
          path: coverage/browser