name: Deploy to Firebase Functions
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Retrieve npm cache (if any)
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-packages
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          ENV_NUBELA_ACCESS_TOKEN: ${{ secrets.NUBELA_ACCESS_TOKEN }}
          ENV_LINKEDIN_USER: ${{ secrets.LINKEDIN_USER }}
          ENV_FIREBASE_USER_UID: ${{ secrets.FIREBASE_USER_UID }}
          ENV_FIREBASE_USER_TOKEN: ${{ secrets.FIREBASE_USER_TOKEN }}

      - name: Create firebase.sdk.key.json file
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "firebase.sdk.key.json"
          json: ${{ secrets.FIREBASE_SDK_KEY }}
          dir: '/'

      - name: Install dependencies
        run: npm install

      - name: Build NestJS project
        run: npm run build

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Functions
        run: 'firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }} --project ${{ secrets.FIREBASE_PROJECT_ID }}'