name: '🧬 Release'

on:
  push:
    branches:
      master

jobs:

  call-node_modules:
    uses: ./.github/workflows/_node_modules.yml

  call-build:
    needs: call-node_modules
    uses: ./.github/workflows/_old_build.yml

  call-deploy:
    needs: call-build
    uses: ./.github/workflows/_old_deploy.yml