name: '🧬 Release'

on:
  push:
    branches:
      master

jobs:

  Test:
    uses: ./.github/workflows/server/test.yml
    secrets: inherit

  Build:
    needs: Test
    uses: ./.github/workflows/server/_build.yml
    secrets: inherit

  Deploy:
    needs: Build
    uses: ./.github/workflows/server/_deploy.yml
    secrets: inherit