name: '🧬 Release'

on:
  push:
    branches: main

jobs:

  #call-node_modules:
    #uses: .github/workflows/_node_modules.yml@main

  #call-test:
    #needs: call-node_modules
    #uses: .github/workflows/_test.yml@main

  call-build:
    needs: call-test
    uses: .github/workflows/old/_build.yml@main

  call-deploy:
    needs: call-deploy
    uses: .github/workflows/old/_deploy.yml@main
    #uses: .github/workflows/deploy/_npm.yml@main
    #with:
      #version: 3.0.0