name: '🧬 Release'

on:
  push:
    branches:
      master

jobs:

  Prueba:
    name: Prueba hola mundo desde actions
    runs-on: ubuntu-latest
    steps:
      
      - name: ✅ Checkout branch
        uses: actions/checkout@v3

      - name: Prueba Hola mundo
        uses: ./.github/actions/action.yml
        with:
          name: 'Matias Diaz'


  Test:
    uses: ./.github/workflows/_test.yml

  Build:
    needs: Test
    uses: ./.github/workflows/_build.yml

  Deploy:
    needs: Build
    uses: ./.github/workflows/_deploy.yml