name: '🧬 Release'

on:
  push:
    branches:
      master

jobs:

  Test:
    uses: ./.github/workflows/_test.yml

  Build:
    needs: Test
    uses: ./.github/workflows/_build.yml

  Deploy:
    needs: Build
    uses: ./.github/workflows/_deploy.yml