name: '🧬 Release'

on:
  push:
    branches: main

jobs:

  #call-node_modules:
    #uses: .github/workflows/_node_modules.yml@main

  call-build:
    needs: call-test
    uses: matidiaz00/matidiaz-api/.github/workflows/_old_build.yml@main

  call-deploy:
    needs: call-deploy
    uses: matidiaz00/matidiaz-api/.github/workflows/_old_deploy.yml@main